# 1.Array Basics 

In [6]:
import numpy as np   #importing numpy library
a =np.array([1,2,3]) # establishing as an array
a
 

1

In [5]:
b = np.array([[1.5,2.6,3.8],[2.5,7.5,6.2]]) # 2 dimensional float array
b

array([[1.5, 2.6, 3.8],
       [2.5, 7.5, 6.2]])

In [10]:
a.ndim # calculating the dimension of the array


1

In [11]:
b.ndim # calculating the dimension of the array

2

In [12]:
a.shape  # calculating the shape of the array i.e number of rows and no of columns

(3,)

In [13]:
b.shape # calculating the shape of the array i.e number of rows and no of columns

(2, 3)

In [14]:
len(a) # a is uni dimensional array so the len counts the numbe of elements in it

3

In [15]:
len(b) # b is two dimensional array so len counts number of one dimensional array or no of rows which is two

2

# 2.Repeat

In [18]:
np.array([1,2,3]*4) # repeat the array by 4 times

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [21]:
np.repeat([7,8,9], 2)# repeat the array by  each element wise

array([7, 7, 8, 8, 9, 9])

In [29]:
np.repeat([[5,6,7],[3,4,5]], 2,axis=0) # repeating along the rows for axis =0 for 2 dimensional array

array([[5, 6, 7],
       [5, 6, 7],
       [3, 4, 5],
       [3, 4, 5]])

In [27]:
m= np.array([[3,4,5]])
m

array([[3, 4, 5]])

In [28]:
np.repeat(m,3,axis=0)

array([[3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

In [31]:
np.repeat(m,3,axis=1)# repeating along the columns for axis =1 for 2 dimensional array

array([[3, 3, 3, 4, 4, 4, 5, 5, 5]])

In [38]:
([m]*4) # establishing m as an array and then repeating the array by 4 times

[array([[3, 4, 5]]),
 array([[3, 4, 5]]),
 array([[3, 4, 5]]),
 array([[3, 4, 5]])]

In [39]:
q=np.array([6,1,9])
q

array([6, 1, 9])

In [40]:
np.tile(m,reps=2) # alternatively you can use tile class to repeat the whole the array

array([[3, 4, 5, 3, 4, 5]])

In [41]:
np.tile(m,reps=(2,1))# repeating the array both row and columnwise

array([[3, 4, 5],
       [3, 4, 5]])

# Basic Mathematics

In [43]:
i=np.array([4,7,8])
i

array([4, 7, 8])

In [44]:
i+2 #basic addition adds 2 element to each individual in an array

array([ 6,  9, 10])

In [45]:
i-2 #basic substraction decreases by 2 element to each individual in an array

array([2, 5, 6])

In [46]:
i/2 #basic division

array([2. , 3.5, 4. ])

In [48]:
i*2 #basic multiplication

array([ 8, 14, 16])

In [49]:
i**2 # two ** means exponent i.e 4*4

array([16, 49, 64])

In [50]:
np.sqrt(i) #square root of an array

array([2.        , 2.64575131, 2.82842712])

Calculating basic Trignometry functions

In [51]:
np.sin(i)

array([-0.7568025 ,  0.6569866 ,  0.98935825])

In [52]:
np.cos(i)

array([-0.65364362,  0.75390225, -0.14550003])

In [53]:
np.tan(i)

array([ 1.15782128,  0.87144798, -6.79971146])

In [54]:
j=np.array([1,4,7])
j

array([1, 4, 7])

In [56]:
i+j
i-j

array([3, 3, 1])

In [57]:
i/j

array([4.        , 1.75      , 1.14285714])

In [58]:
i**j

array([      4,    2401, 2097152])

In [60]:
np.dot(i,j) # dot product refers to element wise product and sum like 4*1+7*4+8*7 for [4,7,8][1,4,7]

88

In [68]:
p=np.array([[1,2,3],[3,4,5]])
p

array([[1, 2, 3],
       [3, 4, 5]])

In [69]:
q=np.array([[3,4],
           [8,9],[7,0]])
q

array([[3, 4],
       [8, 9],
       [7, 0]])

In [70]:
np.dot(p,q) # no of columns in first array must match with no of rows in second array for dot product the end result will follow the shape of second array

array([[40, 22],
       [76, 48]])

In [72]:
np.matmul(p,q) # not applicable for one dimensional array

array([[40, 22],
       [76, 48]])

# Statistics 

In [73]:
o=np.array([1,9,6,7,7,0,-1,2,3])
o

array([ 1,  9,  6,  7,  7,  0, -1,  2,  3])

In [74]:
o.sum()

34

In [75]:
o.max()

9

In [76]:
o.min()


-1

In [77]:
o.std()

3.3591592128513272

In [78]:
o.argmin() # gives the index of the minumum value in array

6

In [79]:
o.argmax()  # gives the index of the max value in array

1

Intialising Different Types of Array

In [82]:
np.arange(9) # intialising an array always excludes the upper limit which is 9 at this example

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [83]:
np.arange(9)**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64])

In [84]:
np.arange(3,12,3)  # 0 is lowerlimit 12 is upperlimit and 3 is the interval

array([0, 3, 6, 9])

In [86]:
np.linspace(0,3,12) # 0 is lowerlimit 3 is upperlimit and 12 is the num of elements , it automatically generates 3 equally spaced element from 0 to 3 

array([0.        , 0.27272727, 0.54545455, 0.81818182, 1.09090909,
       1.36363636, 1.63636364, 1.90909091, 2.18181818, 2.45454545,
       2.72727273, 3.        ])

In [87]:
np.linspace(3,30,10)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.])

In [90]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [91]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [92]:
np.full((2,2), 20) # creates identical matrix 

array([[20, 20],
       [20, 20]])

In [93]:
x = np.array([[1,5],[6,7]])
x

array([[1, 5],
       [6, 7]])

In [94]:
np.full_like(x,4)

array([[4, 4],
       [4, 4]])

In [95]:
np.identity(6) # having same no of rows and columns identity matrix all elements are zero except diagonal ones

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [97]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [98]:
v = np.array([3,6,9])
np.diag(v)

array([[3, 0, 0],
       [0, 6, 0],
       [0, 0, 9]])

# Reorganising or Reorganising Arrays

In [101]:
l= np.arange(4,20,4)
l

array([ 4,  8, 12, 16])

In [104]:
l.reshape(2,2)

array([[ 4,  8],
       [12, 16]])

In [105]:
l.ravel() # to change into default original shape

array([ 4,  8, 12, 16])

In [106]:
i=np.array([[1,2,3],[8,9,0],[1,5,6]])
i

array([[1, 2, 3],
       [8, 9, 0],
       [1, 5, 6]])

In [108]:
i.reshape(1,9)

array([[1, 2, 3, 8, 9, 0, 1, 5, 6]])

In [110]:
i.T

array([[1, 8, 1],
       [2, 9, 5],
       [3, 0, 6]])

# Indexing or Slicing


In [111]:
u=np.array([2,1,3,4,5,6,7,8,9])
u[2] # 2nd position of the array

3

In [112]:
u[1:6] # here 1 is lower element and 6 is thae upper limit

array([1, 3, 4, 5, 6])

In [120]:
u[1::3]#1 is starting index and 2 is the interval

array([1, 5, 8])

In [115]:
u[1::2][0:3] # to eliminate 8 from the list so only index 0,1 and 2 pass

array([1, 4, 6])

In [116]:
u[4:]

array([5, 6, 7, 8, 9])

In [117]:
u[:3]

array([2, 1, 3])

In [118]:
u[2:6:2] #2 is starting index and 6 is the last index  and 2 is the interval

array([3, 5])

In [122]:
u[-4::2] # here -4 means the 4th  element from the end so it starts from that element  and moves up till the end

array([6, 8])

In [123]:
u[-4::-2]

array([6, 4, 1])

## 2D Array Slicing and Indexing

In [127]:
k=np.arange(3,45).reshape(6,7)
k

array([[ 3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43, 44]])

In [128]:
k[0] #printing thr rows

array([3, 4, 5, 6, 7, 8, 9])

In [129]:
k[:,3] #printing the columns

array([ 6, 13, 20, 27, 34, 41])

In [131]:
k[4,5] # to get the exact value from the matrix look for their position as always start with zero

36

In [132]:
k[4,2]

33

In [133]:
k[0:3,1] # getting the first three elements of second column

array([ 4, 11, 18])

In [134]:
k[2:5,0:2]

array([[17, 18],
       [24, 25],
       [31, 32]])

In [135]:
k[3:5,3:6] # first element defines the index of rows and columns t intiate and second one being the end one 

array([[27, 28, 29],
       [34, 35, 36]])

In [136]:
k[0::2] # printing every second row where 0 is start index and 2 is the interval

array([[ 3,  4,  5,  6,  7,  8,  9],
       [17, 18, 19, 20, 21, 22, 23],
       [31, 32, 33, 34, 35, 36, 37]])

In [137]:
k[:,0::2]# printing every second column where 0 is start index and 2 is the interval

array([[ 3,  5,  7,  9],
       [10, 12, 14, 16],
       [17, 19, 21, 23],
       [24, 26, 28, 30],
       [31, 33, 35, 37],
       [38, 40, 42, 44]])

## 3D Array Slicing and Indexing

In [143]:
x =np.arange(45).reshape(3,3,5)
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [140]:
x[2]# selecting the part of the array

array([[30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [141]:
x[2][1] # printing the second row 

array([35, 36, 37, 38, 39])

In [142]:
x[2][:,2] #printing the third column

array([32, 37, 42])

In [144]:
x[1][1][3]# exttracting 3 from the array 

23

In [145]:
x[1:,0] # getting the first rows of second and third array

array([[15, 16, 17, 18, 19],
       [30, 31, 32, 33, 34]])

In [146]:
x[1:,0:2,1:4]# all target elements are in second and third 2D array so we can select with x[1:] 0:2 represents first and second row and 1;4 represents column from second to 4th

array([[[16, 17, 18],
        [21, 22, 23]],

       [[31, 32, 33],
        [36, 37, 38]]])

In [149]:
x[0:2,1:3,2:5]#0:2 represents target element in first and second element 1:3 represents second and third row,2:5 represents third to fourth column

array([[[ 7,  8,  9],
        [12, 13, 14]],

       [[22, 23, 24],
        [27, 28, 29]]])

# Adding Rows or Columns

In [151]:
b=[[7,8,9,8],[1,4,7,0]]
g=[1,0,9,8]
np.vstack([b,g]) # stacking the list vertcially

array([[7, 8, 9, 8],
       [1, 4, 7, 0],
       [1, 0, 9, 8]])

In [152]:
np.vstack([b,g,b])

array([[7, 8, 9, 8],
       [1, 4, 7, 0],
       [1, 0, 9, 8],
       [7, 8, 9, 8],
       [1, 4, 7, 0]])

In [153]:
np.array(b)
np.array(g)

array([1, 0, 9, 8])

In [154]:
y=np.ones((2,3))
y

array([[1., 1., 1.],
       [1., 1., 1.]])

In [155]:
np.hstack([b,y]) # stacking the list horizontally

array([[7., 8., 9., 8., 1., 1., 1.],
       [1., 4., 7., 0., 1., 1., 1.]])

Concatenate

In [156]:
t=[[2,3,4,5],[1,2,3,5]]
c=[[1,2,2,4]]
np.concatenate((t,c), axis=0) # for concatenating both list must be of same dimension 

array([[2, 3, 4, 5],
       [1, 2, 3, 5],
       [1, 2, 2, 4]])

In [157]:
i=[[1,2],[3,4]]
j=[[6,7],[9,0]]
np.concatenate((i,j),axis=1) # for concatenating horizontally no of rows should be same in both array

array([[1, 2, 6, 7],
       [3, 4, 9, 0]])

## Append, Insert ,Delete and Sort

In [168]:
k=np.array([1,2,3])
l=np.array([4,5,6])
m=np.array([4,5,0])

In [169]:
l

array([4, 5, 6])

In [171]:
np.append([[1,3,5],[4,3,6]],[[6,7,8]], axis=0)

array([[1, 3, 5],
       [4, 3, 6],
       [6, 7, 8]])

# #Insert

In [173]:
y=np.array([[1,2,3],[4,5,6],[7,8,9]])
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [174]:
np.insert(y,0,9)

array([9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [175]:
np.insert(y,1,9,axis=1) # adding columns of 9 in index 1

array([[1, 9, 2, 3],
       [4, 9, 5, 6],
       [7, 9, 8, 9]])

In [176]:
np.insert(y,1,9,axis=0) # adding rows of 9 in index 1

array([[1, 2, 3],
       [9, 9, 9],
       [4, 5, 6],
       [7, 8, 9]])

In [177]:
g=np.array([[2,1,3,4],[2,2,3,2],[5,1,2,3]])
g

array([[2, 1, 3, 4],
       [2, 2, 3, 2],
       [5, 1, 2, 3]])

In [180]:
np.delete(g,[2,2,3,2],axis=1)

array([[2, 1],
       [2, 2],
       [5, 1]])

In [181]:
g.flatten()

array([2, 1, 3, 4, 2, 2, 3, 2, 5, 1, 2, 3])

# #Sort

In [184]:
np.sort(g)

array([[1, 2, 3, 4],
       [2, 2, 2, 3],
       [1, 2, 3, 5]])

In [185]:
np.sort(g,axis=None)

array([1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 4, 5])

In [186]:
np.sort(g,axis=0)

array([[2, 1, 2, 2],
       [2, 1, 3, 3],
       [5, 2, 3, 4]])

In [187]:
np.sort(g,axis=1)

array([[1, 2, 3, 4],
       [2, 2, 2, 3],
       [1, 2, 3, 5]])

In [188]:
np.flip(g,0)

array([[5, 1, 2, 3],
       [2, 2, 3, 2],
       [2, 1, 3, 4]])

In [189]:
np.flip(g,1)

array([[4, 3, 1, 2],
       [2, 3, 2, 2],
       [3, 2, 1, 5]])

# #Random

In [190]:
np.random.rand()

0.09290535980967984

In [191]:
np.random.rand(2,3)

array([[0.53381317, 0.28695716, 0.16341719],
       [0.57479638, 0.57702063, 0.34894054]])

In [192]:
np.random.randint(20)

11

In [193]:
np.random.randint(1,25,5)

array([ 2, 10,  1,  5,  5])

In [194]:
np.random.randint(1,100,(4,4))

array([[ 3, 64, 10, 81],
       [10, 68, 68, 15],
       [64, 38, 76,  6],
       [74, 60,  7, 31]])

In [195]:
i=np.array([3,4,5,6,7,8])
np.random.shuffle(i)
i

array([6, 5, 4, 3, 8, 7])

## Save, Load and Import File

In [196]:
np.save('new',g)

In [197]:
np.load('new.npy')

array([[2, 1, 3, 4],
       [2, 2, 3, 2],
       [5, 1, 2, 3]])